name: Ping Streamlit App

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ping SPAE Standalone (Health Endpoint)
        run: curl -sL https://spae-standalone-afywudedgwmqxj4qgb3qvn.streamlit.app/_stcore/health > /dev/null

      - name: Keep GitHub Action Alive
        uses: gautamkrishnar/keepalive-workflow@v1
